class Locations:
    Trinsic = "Trinsic"
    Skae_Brae = "Skae Brae"
    Britain = "Britain"
    Britannia = "Britannia"
    Paws = "Paws"
    Empville = "Empville"
    Buccaneers_Den = "Buccaneer's Den"
    The_Dungeon_Destard = "The Dungeon Destard"
    Lord_BlackThornsCastle = " Lord BlackThorns Castle"
